---

  - name: Add dc1.dac.local to /etc/hosts file
    lineinfile:
      dest: /etc/hosts
      line: 172.20.32.2 dc1 dc1.dac.local
      backup: yes

  - name: SSSD config
    notify: enable SSSD
    copy:
      src: etc/sssd/sssd.conf
      dest: /etc/sssd/sssd.conf
      backup: yes
      mode: 0600
      owner: root
      group: root

  - name: Home dirs with pam_mkhomedirs
    lineinfile:
      create: yes
      dest: /etc/pam.d/common-session
      regexp: session\s+required\s+pam_mkhomedir.so\s+skel=/etc/skel/\s+umask=0022
      line: 'session	required	pam_mkhomedir.so skel=/etc/skel/ umask=0022'
      insertafter: session\s+required\s+pam_unix.so

  - name: Configure Lightdm login
    ini_file:
      backup: yes
      dest: /etc/lightdm/lightdm.conf
      section: '{{ item.section }}'
      option: '{{ item.option }}'
      value: '{{ item.value }}'
    with_items:
      - section: SeatDefaults
        option: greeter-show-manual-login
        value: 'true'
      - section: SeatDefaults
        option: greeter-hide-users
        value: 'true'

  - name: Configure samba
    lineinfile:
      dest: /etc/samba/smb.conf
      regexp: '\s*{{ item.option }}\s*='
      line: '{{ item.option }} = {{ item.value }}'
      insertafter: '\[global\]'
    with_items:
      - option: realm
        value: dac.local
      - option: client signing
        value: 'yes'
      - option: client use spnego
        value: 'yes'
      - option: kerberos method
        value: secrets and keytab
      - option: workgroup
        value: dac
      - option: security
        value: ads
    tags: samba


  # - name: Configure Kerberos
  #   ini_file:
  #     backup: yes
  #     dest: /etc/krb5.conf
  #     section: '{{ item.section }}'
  #     option: '{{ item.option }}'
  #     value: '{{ item.value }}'
  #   with_items:
  #     - section: libdefaults
  #       option: default
  #       value: DAC.LOCAL
  #     - section: libdefaults
  #       option: default_realm
  #       value: DAC.LOCAL
  #     - section: domain_realm
  #       option: .dc1.dac.local
  #       value: DC1.DAC.LOCAL
  #     - section: domain_realm
  #       option: dc1.dac.local
  #       value: DC1.DAC.LOCAL
  #     - section: realms
  #       option: dummy
  #       value: dummy
  #   tags: krb
  # 
  # - name: Configure Kerberos 2
  #   blockinfile:
  #     backup: yes
  #     dest: /etc/krb5.conf
  #     insertafter: '{{ item.section }}'
  #     block: '{{ item.block }}'
  #     marker: '{{ item.marker }}'
  #   with_items:
  #     - section: \[realms\]
  #       marker: "# {mark} DAC.LOCAL ANSIBLE MANAGED BLOCK"
  #       block: |
  #         DAC.LOCAL = {
  #           kdc = dc1.dac.local
  #           admin_server = dc1.dac.local
  #           default_domain = dac.local
  #         }
  #   tags: krb
