---

  - name: Hostname
    include: hostname.yml

  - name: Packages
    include: packages.yml

  - name: Configure lamp
    include: lamp.yml

  - name: Configure AD
    include: ad.yml

  - name: Configure sshd and keys
    include: ssh.yml
