---

  - name: start SSSD
    service:
      name: sssd
      state: started

  - name: restart SSSD
    service:
      name: sssd
      state: restarted

  - name: enable SSSD
    service:
      name: sssd
      enabled: yes
  
  - name: restart apache
    service:
      name: apache2
      state: restarted
